spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 9901
  
logging:
  file: /logs/apollo/100003172/apollo-adminservice.log
